### ISSUE TITLE
New language-spice package

### ISSUE THREAD

**Issue by Bollos00** [timerg/language-spice#1]
Good morning/afternoon/night @timerg,

First of all thank you for maintaining this package on the last four to five years. I have been using spice very much this last semester and figured out that a lot of functionalities were missing, so I decided to contribute to implement new features of the SPICE language.

Firstly I had forked this repository, but soon I figured out that I had another perspective on the development of this package and basically all of the code that was in this package would be removed, then I decided to start a new package from scratch, and I did it, see https://github.com/Bollos00/language-spice

I have just finish that last implementation that I wanted to do and I think that it is ready for be released.

The README file on the repository will show an example of circuit netlist written with SPICE language on the atom text editor with the syntax that I have developed, as I said before, I had another approach on how to capture circuit elements (resistors, capacitors etc), how to define the dot commands (`.model`, `.subckt` and so on), and the nodes on the circuit, that is the reason I started a new one from scratch.

I have also added new snippets to help the user to write the circuit netlist, those snippets can be identified on the package page inside atom, as the image below

![Screenshot from 2020-12-01 16-39-29](https://user-images.githubusercontent.com/53309405/100788367-bb74de00-33f3-11eb-9e22-16720f993eb2.png)

Another two examples with this syntax are shown below

![Screenshot from 2020-12-01 16-43-27](https://user-images.githubusercontent.com/53309405/100788709-3807bc80-33f4-11eb-9920-4c1ddcf7ecbe.png)
![Screenshot from 2020-12-01 16-42-52](https://user-images.githubusercontent.com/53309405/100788716-3938e980-33f4-11eb-92cd-8260696d187e.png)

I added a lot of functionalities on and it catches most of the features of the language as you can see.

I would like to maintain this package the [atom official repositories](https://atom.io/packages/language-spice) if this is okay with you. Since you have developed and maintained the current package for very long I would mark you as a contributor of the package, so you would still receive the credit.

Please let me know what you think about offer,

Sincerely,
@Bollos00

**Comment by timerg** [comment]
@Bollos00 I'm so sorry that I completely missed this issue because I have not use spice for many years. I will refer your project in the readme and archive mine. Best regards
